baseurl = "https://drakarenmatida.com/" # Hostname (and path) to the root.
title = "Dra. Karen Tamae Matida" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

[pagination]
pagerSize = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Dra. Karen Tamae Matida" # Author's name.
    info = "Endocrinologia e Metabologia" # Author's job title or info.
    description = "Dra. Karen Tamae Matida's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "https://s3-sa-east-1.amazonaws.com/doctoralia.com.br/doctor/cba87a/cba87a6b484aad73cfc1f0082dc6c36f_large.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 1
    url = "https://www.instagram.com/drakarenmatida.endocrino/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/karen-matida"

# Menu links
[[menu.main]]
    name = "Agendar consulta"
    weight = 1
    url  = "https://www.doctoralia.com.br/karen-matida/especialista-em-clinica-medica-endocrinologista/indaiatuba"
